[package]
name = "sfx_daw"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
symphonia = { version = "0.5.4", features = ["opt-simd", "all-formats", "all-codecs"] }
rubato = "0.16.1"
rustfft = "6.2.0"
