[package]
name = "sfx_daw"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
symphonia = { version = "0.5.4", features = ["opt-simd"] }

[patch.crates-io]
symphonia = { path = "../Symphonia/symphonia" }